# Histogrammer 
histogrammer:
  min_depth: !Quantity 0.0 meters
  max_depth: !Quantity 10.0 meters
  n_bins: 1000
  bin_width: !Quantity 0.014 meters
  pixel_fov_list: [[0, 0.1, 0, 0.1], [0, 0.1, 0.1, 0.2], [0, 0.1, 0.2, 0.3], [0, 0.1, 0.3, 0.4]]
  vignette: false 
  n_pulses: 1000
  dead_time_s: !Quantity 0 nanoseconds
  free_running: False

# Active Light Source 
active_source:
  pulsed_laser:
    enabled: true
    wavelength: !Quantity 940.0 nanometers            # nanometers
    frequency: !Quantity 10.0 megahertz               # hertz
    pulse_width: !Quantity 1.5 nanoseconds            # seconds
    avg_watts: !Quantity 0.001 watts                    # watts
    pulse_shape: "gaussian"         # "gaussian", "square", or "custom" 
    # pulse_shape_custom: "lambda x: np.sinc(x / 3)"
    pulse_shape_custom: [0,1,2,3,4,5,6,5,4,3,2,1,0]

# Ambient Light Sources 
ambient_source:
  sun:
    enabled: true
    temperature: !Quantity 5778.0 kelvin            # kelvin
    light_conditions: "AVERAGE_SUNLIGHT"  # from LightConditions enum
    lambda_pass: !Quantity 550.0 nanometers             # nanometers
    delta_lambda: !Quantity 10.0 nanometers             # nanometers
    intensity: !Quantity 3.828e26 watt / meter**2      # watts per square meter
# Sensor
sensor:
  size: [5, 5]          # [height, width]
  pixel_pitch: !Quantity 10.0 micrometer           # meters
  f_number: !Quantity 1.4         # dimensionless
  fov: !Quantity [90.5 degree, 90.5 degree]
