# Histogrammer 
histogrammer:
  min_depth: 0.0
  max_depth: 40.0
  n_bins: 100
  shape: [300, 400]  # [height, width] to match sensor size
  strict_units: true
  strict_range: false
  bin_width: 0.03  # meters per bin
  pixel_fov_list: [[0, 0.4, 0.3, 0.6], [0.2, 0.45, 0.6, 0.8]]
  n_pulses: 10000   # number of laser pulses
  dead_time_s: 0 # Dead time in seconds
  free_running: False # Free-running mode (True) or gated mode (False) 

# Active Light Source 
active_source:
  pulsed_laser:
    enabled: true
    wavelength: !Quantity 550.0 nanometers            # nanometers
    frequency: !Quantity 10.0 megahertz               # hertz
    pulse_width: !Quantity 2.5 nanoseconds            # seconds
    avg_watts: !Quantity 1.0 watts                    # watts
    pulse_shape: "gaussian"         # "gaussian", "square", or "custom" 
    # pulse_shape_custom: "lambda x: np.sinc(x / 3)"
    pulse_shape_custom: "np.array([0,0,0.0,0.0,0.1,0.3,1,0.9,0.8,0.4,0.1,0,0])"
    
# Ambient Light Sources 
ambient_source:
  sun:
    enabled: true
    temperature: !Quantity 5778.0 kelvin            # kelvin
    light_conditions: "OVERCAST"  # from LightConditions enum
    lambda_pass: !Quantity 550.0 nanometers             # nanometers
    delta_lambda: !Quantity 10.0 nanometers             # nanometers
    intensity: !Quantity 3.828e26 watts / meter**2      # watts per square meter
    stability_factor: !Quantity 0.01                    # dimensionless
    
  flickering_lamp:
    enabled: true
    temperature: !Quantity 2700.0 kelvin           # kelvin (typical incandescent bulb)
    illuminance: !Quantity 800.0 lux               # lux (typical room lighting)
    modulation_frequency: !Quantity 120.0 hertz    # hertz (AC power frequency)
    modulation_amplitude: !Quantity 0.1            # dimensionless (10% flicker)
    phase: !Quantity 0.0 radians                   # radians
    pulse_width: !Quantity 0.001 seconds           # seconds
    pulse_shape: "gaussian"
    emissivity: 0.9              # dimensionless

# Sensor
sensor:
  size: [300, 400]          # [height, width]
  pixel_pitch: !Quantity 10.0 micrometer           # meters
  f_number: !Quantity 1.4         # dimensionless
  fov: !Quantity [66 degree, 44 degree]