"""
This is a temporary module which contains all the base classes for the active spc emulator support.
The classes will be modified/moved to different sub-packages as required. 

General NOTE: When implementing all the functions ensure that they support differentiable pipelines. 

"""

from __future__ import annotations

import numpy as np
import numpy.typing as npt


#######################################
# Classes related to scene properties #
#######################################

class LightSource:
    """Base class for any type of light source, active, passive, constant, time varying etc.    
    Any type of light source must inherit this class"""
    def __init__(self):
        pass

class ConstantSource(LightSource):
    """
    Base class for any light source which has constant light intensity over time."""
    def __init__(self):
        pass

class DynamicSource(LightSource):
    """
    Base class for any time varying light source. Can model flicker or AC light sources?
    """
    def __init__(self):
        pass

# Encode scene geometry #
#########################


class RGBDStream:
    """Base class to load an RGBD stream from existing datasets."""
    def __init__(self: int):
        """_summary_
        Use RGBStream to extract instances and avoid the sense of absolute time right now. 
        The data loader will decide the batch size based on the required FPS.
        Args:
                    
        ..note:: Can add 
            - Undistortion method? One option is to assume that the RGBD images are already undistorted?
            - Dictionary to pass all the camera parameters?
        """

    def batch_frames(self,batch_size: int):
        """_summary_
        Needs to be moved to a dataloader class to decide the number of frames.

        Args:
            batch_size (int): Combines multiple RGBD frames to enable SPC histograms generated by combining multiple histograms
        """



########################
# Single Photon Camera #
########################

class Sensor:
    """A high-level sensor class which will act like a driver that glues all the components, like the active source,
    detector, histogrammer etc.

    This base class will be inherited by other sensor classes that might treat different elements in a unique way.
    
    """
    def __init__(self):
        pass
    


class Detector:
    """Base class to set SPC detector properties

    Include optical characteristics:
    - Use From RGBD stream or custom calibration params (focal length, optical center, distortion params etc).
    - Band pass filter/ optical attenuation
    - Sensor FOV per pixel:
        Includes:
        * Output resolution
        * FoV for each pixel (This feature will allow lazy evaluation of high-res transients)
        * Optical effects like vignetting effect
        * Can also add effect of dead pixels consider real hardware
    - Pixel properties:
        * Pixel dimensions
        * Pitch/Area
        * Photon detection efficiency
        * Detector dead time/ Sensor dead time Td
        * Fill factor 
        * dark current
    """
    def __init__(self):
        pass

class ActiveSource(LightSource):
    """Base class for active illumination source used by the SPAD camera
    
    Includes:
        * pulse wavelength
        * Laser power
        * Total photons per cycle
        * Time period/ rep-rate
        * Time jitter
    Modeling choice:
        * Assume a gaussian pulse with known sigma
        * Use a custom IRF (Allows better hardware emulation)
    """
    def __init__(self):
        pass

class Histogrammer:
    """Base class for all types of histogrammers.

    NOTE: The user must decide using interpolation/ rendering parameters to first generate all the RGBD frames first 
    
    Includes:
        * Synchronization details (Synchronous, Free running, Asynchronous with deterministic shift)
        * Will act as the main code that controls the interaction between the ActiveSource and Detector instances.
        * Takes a dictionary or param file that contains all the properties of the Active source, 
            detector instances, TDC resolution etc.
        * Timing circuit details:
            - TDC resolution
            - Timing electronics dead time Te
    """

    def __init__(self):
        pass

    def generate_transient(self, fov_masks: npt.NDArray[np.floating]):
        """Takes input FOV mask to generate intermediate transients for desired pixels based on fov masks.

        ..note:: Design some uniform method of passing RGB, Depth, Scene albedo, Scene Reflectance etc. 

        This class interacts with the RGBDStream class, to get RGB, and depth data, and illumination sources.

        Args:
            fov_masks (npt.NDArray[np.floating]): 3D or 4D mask that determines the which pixels of which 
                    frame number are used to compute the transient and the SPC data. 3D mask for a single RGB-D 
                    frame for desired K pixels and a 4D mask to include the temporal aspect if we want to use multiple 
                    RGB-D frames to generate the transient and histograms (simulate motion artifacts).
        """

    def simulate_photons(self, tr: npt.NDArray[np.floating]):
        """Simulate photon timestamps based on the transient (tr)

        Args:
            tr (npt.NDArray[np.floating]): _description_
        """


class BaseEWH:
    """Base class for SPCs using equi-width histogrammers. 

    Includes:
        * Number of EWH bins
        * Shifted time gates (different max range than active illumination)?
        * Precision/ bit depth?
    """
