name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        blender-version: ["3.3", "4.5", "latest"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ACT dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y
          sudo apt-get update -y
          sudo apt-get install -y lsb-release
          sudo apt-get install -y tar xz-utils git ffmpeg wget nano bzip2 
          sudo apt-get install -y --no-install-recommends --fix-missing libxi6 libxkbcommon-x11-0 libglfw3-dev libgles2-mesa-dev libsm6
      - name: Install Blender
        uses: bradyajohnston/setup-blender@v5
        with:
          version: ${{ matrix.blender-version }}
      - name: Install ffmpeg
        uses: federicocarboni/setup-ffmpeg@v3
      - name: Check Dependencies 
        run: | 
          blender --version
          ffmpeg -version 
      - name: Install VisionSim and dependencies
        run: |
          # Force torch to use CPU
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu 
          pip install -e . --group dev 
          vsim post-install --editable
      - name: Run Tests
        run: |
          pytest --durations=0 -s
