name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        blender-version: ["3.6", "4.5", "latest"]
        # os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ACT dependencies
        if: ${{ env.ACT }}
        run: |
          # Update docker image
          apt-get update && apt-get install sudo -y
          sudo apt-get update -y

          # Packages needed for blender
          sudo apt-get install -y lsb-release
          sudo apt-get install -y tar xz-utils git ffmpeg wget nano bzip2 
          sudo apt-get install -y --no-install-recommends --fix-missing libxi6 libxkbcommon-x11-0 libglfw3-dev libgles2-mesa-dev libsm6

          # Install ffmpeg directly as the setup-ffmpeg needs to interact with the gh cli and have access to gh tokens
          sudo apt-get install -y ffmpeg
      - name: Install ffmpeg
        if: ${{ !env.ACT }}
        uses: AnimMouse/setup-ffmpeg@v1
      - name: Install Blender
        uses: bradyajohnston/setup-blender@v5
        with:
          version: ${{ matrix.blender-version }}
      - name: Install VisionSim and dependencies
        run: |
          # Force torch to use CPU
          pip install torch --index-url https://download.pytorch.org/whl/cpu 
          pip install -e . --group dev 
          vsim post-install --editable
      - name: Check Dependencies 
        run: | 
          blender --version
          blender --background --python-use-system-env --python-expr "import visionsim"
          ffmpeg -version 
      - name: Run Tests
        run: |
          pytest --durations=0 -s
