name: CLI Installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff .
      - name: Install Spsim and dependencies
        run: |
          pip install .
      - name: Install FFmpeg
        run: |
          sudo apt-get install ffmpeg
          ffmpeg -version
      - name: Install Blender
        run: |
          sudo snap install blender --classic --channel=3.3lts/stable
          echo -n "BLENDER_PY=$(blender --background --python-expr 'import sys; print(sys.executable, file=sys.stderr)' 2>&1 >/dev/null)" >> $GITHUB_ENV
      - name: Install Blender dependencies
        run: |
          echo "Found blender python interpreter at $BLENDER_PY"
          $BLENDER_PY -m ensurepip
          $BLENDER_PY -m pip install scipy rich
      - name: Test cli
        run: |
          spsim -l
