name: CLI Installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff check --extend-select I tasks.py visionsim/ tests/
      - name: Install FFmpeg
        run: |
          sudo snap install ffmpeg
          ffmpeg -version
      - name: Install Blender
        run: |
          sudo snap install blender --classic --channel=3.3lts/stable
          blender --version
      - name: Install VisionSim and dependencies
        run: |
          pip install .[dev]
          vsim post-install --editable
      - name: Build Docs
        run : |
          inv build-docs
      - name: Run Tests
        run: |
          pytest --durations=0
